# Numpy Problems

In [1]:
import numpy as np 
import pandas as pd

In [2]:
mpg = pd.read_csv(r'/Users/renchulaji/Desktop/auto-mpg.csv')

In [3]:
mpg

mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130    3504          12.0   
1    15.0          8         350.0        165    3693          11.5   
2    18.0          8         318.0        150    3436          11.0   
3    16.0          8         304.0        150    3433          12.0   
4    17.0          8         302.0        140    3449          10.5   
..    ...        ...           ...        ...     ...           ...   
393  27.0          4         140.0         86    2790          15.6   
394  44.0          4          97.0         52    2130          24.6   
395  32.0          4         135.0         84    2295          11.6   
396  28.0          4         120.0         79    2625          18.6   
397  31.0          4         119.0         82    2720          19.4   

     model year  origin                   car name  
0            70       1  chevrolet chevelle malibu  
1            70       1          buick skylark 320  
2            70       1         plymouth satellite  
3            70       1              amc rebel sst  
4            70       1                ford torino  
..          ...     ...                        ...  
393          82       1            ford mustang gl  
394          82       2                  vw pickup  
395          82       1              dodge rampage  
396          82       1                ford ranger  
397          82       1                 chevy s-10  

[398 rows x 9 columns]

1) Basic array Operation
   Convert the mpg column into numpy array and calculate:
    * The mean,median, and standard deviation of mpg
    * The number of cars with mpg greater than 25

In [4]:
pf= pd.DataFrame(mpg)

In [5]:
mpg_array=pf['mpg'].to_numpy()

In [6]:
mpg_array

array([18. , 15. , 18. , 16. , 17. , 15. , 14. , 14. , 14. , 15. , 15. ,
       14. , 15. , 14. , 24. , 22. , 18. , 21. , 27. , 26. , 25. , 24. ,
       25. , 26. , 21. , 10. , 10. , 11. ,  9. , 27. , 28. , 25. , 25. ,
       19. , 16. , 17. , 19. , 18. , 14. , 14. , 14. , 14. , 12. , 13. ,
       13. , 18. , 22. , 19. , 18. , 23. , 28. , 30. , 30. , 31. , 35. ,
       27. , 26. , 24. , 25. , 23. , 20. , 21. , 13. , 14. , 15. , 14. ,
       17. , 11. , 13. , 12. , 13. , 19. , 15. , 13. , 13. , 14. , 18. ,
       22. , 21. , 26. , 22. , 28. , 23. , 28. , 27. , 13. , 14. , 13. ,
       14. , 15. , 12. , 13. , 13. , 14. , 13. , 12. , 13. , 18. , 16. ,
       18. , 18. , 23. , 26. , 11. , 12. , 13. , 12. , 18. , 20. , 21. ,
       22. , 18. , 19. , 21. , 26. , 15. , 16. , 29. , 24. , 20. , 19. ,
       15. , 24. , 20. , 11. , 20. , 21. , 19. , 15. , 31. , 26. , 32. ,
       25. , 16. , 16. , 18. , 16. , 13. , 14. , 14. , 14. , 29. , 26. ,
       26. , 31. , 32. , 28. , 24. , 26. , 24. , 26

In [7]:
mpg_array.dtype

dtype('float64')

In [8]:
mean = np.mean(mpg_array)
median = np.median(mpg_array)
sd = np.std(mpg_array)
print("Mean",mean)
print("Median",median)
print("Standard Deviation",sd)

Mean 23.514572864321607
Median 23.0
Standard Deviation 7.806159061274433


In [9]:
count = np.sum(mpg_array > 25)
print("(MPG > 25):",count)

(MPG > 25): 158


Filtering

* Using Numpy, filter all cars with more than 6 cylinder
* Return the corresponding car_name as list

In [10]:
cylinder = mpg[mpg['cylinders'] == 6]

In [11]:
cylinder

mpg  cylinders  displacement horsepower  weight  acceleration  \
15   22.0          6         198.0         95    2833          15.5   
16   18.0          6         199.0         97    2774          15.5   
17   21.0          6         200.0         85    2587          16.0   
24   21.0          6         199.0         90    2648          15.0   
33   19.0          6         232.0        100    2634          13.0   
..    ...        ...           ...        ...     ...           ...   
365  20.2          6         200.0         88    3060          17.1   
366  17.6          6         225.0         85    3465          16.6   
386  25.0          6         181.0        110    2945          16.4   
387  38.0          6         262.0         85    3015          17.0   
389  22.0          6         232.0        112    2835          14.7   

     model year  origin                           car name  
15           70       1                    plymouth duster  
16           70       1                         amc hornet  
17           70       1                      ford maverick  
24           70       1                        amc gremlin  
33           71       1                        amc gremlin  
..          ...     ...                                ...  
365          81       1                    ford granada gl  
366          81       1             chrysler lebaron salon  
386          82       1              buick century limited  
387          82       1  oldsmobile cutlass ciera (diesel)  
389          82       1                     ford granada l  

[84 rows x 9 columns]

In [12]:
car_names = mpg[mpg['cylinders'] == 6]['car name'].tolist()

In [13]:
car_names

['plymouth duster',
 'amc hornet',
 'ford maverick',
 'amc gremlin',
 'amc gremlin',
 'plymouth satellite custom',
 'chevrolet chevelle malibu',
 'ford torino 500',
 'amc matador',
 'amc hornet sportabout (sw)',
 'pontiac firebird',
 'ford mustang',
 'plymouth valiant',
 'chevrolet nova custom',
 'amc hornet',
 'ford maverick',
 'plymouth duster',
 'amc gremlin',
 'mercury capri v6',
 'toyota mark ii',
 'plymouth duster',
 'ford maverick',
 'amc hornet',
 'chevrolet nova',
 'chevrolet chevelle malibu classic',
 'amc matador',
 'plymouth satellite sebring',
 'plymouth valiant custom',
 'chevrolet nova',
 'mercury monarch',
 'ford maverick',
 'buick century',
 'chevroelt chevelle malibu',
 'amc matador',
 'plymouth fury',
 'buick skyhawk',
 'amc gremlin',
 'ford pinto',
 'amc pacer',
 'plymouth valiant',
 'chevrolet nova',
 'ford maverick',
 'amc hornet',
 'dodge aspen se',
 'ford granada ghia',
 'pontiac ventura sj',
 'amc pacer d/l',
 'toyota mark ii',
 'mercedes-benz 280s',
 'chevrole

Statistical Analysis 
* Compute the 25th, 50th and 75th percentiles of the weight column using Numpy

In [14]:
weight = mpg['weight'].to_numpy()

In [15]:
weight.sort()
weight

array([1613, 1649, 1755, 1760, 1773, 1795, 1795, 1800, 1800, 1825, 1825,
       1834, 1835, 1835, 1836, 1845, 1850, 1867, 1875, 1915, 1925, 1937,
       1937, 1940, 1945, 1950, 1950, 1955, 1963, 1965, 1965, 1968, 1970,
       1975, 1975, 1980, 1985, 1985, 1985, 1985, 1990, 1990, 1995, 2000,
       2003, 2019, 2020, 2025, 2035, 2045, 2045, 2046, 2050, 2051, 2065,
       2065, 2070, 2074, 2075, 2085, 2100, 2108, 2110, 2110, 2120, 2123,
       2124, 2125, 2125, 2125, 2126, 2130, 2130, 2130, 2130, 2135, 2144,
       2145, 2150, 2155, 2155, 2155, 2158, 2160, 2164, 2164, 2171, 2188,
       2189, 2190, 2190, 2200, 2202, 2205, 2210, 2215, 2219, 2220, 2220,
       2223, 2226, 2228, 2230, 2234, 2245, 2246, 2254, 2255, 2264, 2265,
       2265, 2265, 2278, 2279, 2288, 2290, 2295, 2300, 2300, 2300, 2310,
       2320, 2330, 2335, 2350, 2370, 2372, 2375, 2379, 2380, 2385, 2391,
       2395, 2395, 2401, 2405, 2408, 2408, 2420, 2430, 2434, 2451, 2464,
       2472, 2489, 2490, 2500, 2506, 2511, 2515, 25

In [16]:
Twenty_five = np.percentile(weight,25)
Fifty=np.percentile(weight,50)
Seventy_five = np.percentile(weight,75)

In [17]:
print("25th Percentile",Twenty_five)
print("50th Percentile",Fifty)
print("75th Percentile",Seventy_five)

25th Percentile 2223.75
50th Percentile 2803.5
75th Percentile 3608.0


Array Manipulation

* Convert the acceleration column into a NumPY array and normalize its values (Scale between 0 and 1)

In [18]:
acceleration = mpg['acceleration'].to_numpy()

In [19]:
acceleration

array([12. , 11.5, 11. , 12. , 10.5, 10. ,  9. ,  8.5, 10. ,  8.5, 10. ,
        8. ,  9.5, 10. , 15. , 15.5, 15.5, 16. , 14.5, 20.5, 17.5, 14.5,
       17.5, 12.5, 15. , 14. , 15. , 13.5, 18.5, 14.5, 15.5, 14. , 19. ,
       13. , 15.5, 15.5, 15.5, 15.5, 12. , 11.5, 13.5, 13. , 11.5, 12. ,
       12. , 13.5, 19. , 15. , 14.5, 14. , 14. , 19.5, 14.5, 19. , 18. ,
       19. , 20.5, 15.5, 17. , 23.5, 19.5, 16.5, 12. , 12. , 13.5, 13. ,
       11.5, 11. , 13.5, 13.5, 12.5, 13.5, 12.5, 14. , 16. , 14. , 14.5,
       18. , 19.5, 18. , 16. , 17. , 14.5, 15. , 16.5, 13. , 11.5, 13. ,
       14.5, 12.5, 11.5, 12. , 13. , 14.5, 11. , 11. , 11. , 16.5, 18. ,
       16. , 16.5, 16. , 21. , 14. , 12.5, 13. , 12.5, 15. , 19. , 19.5,
       16.5, 13.5, 18.5, 14. , 15.5, 13. ,  9.5, 19.5, 15.5, 14. , 15.5,
       11. , 14. , 13.5, 11. , 16.5, 17. , 16. , 17. , 19. , 16.5, 21. ,
       17. , 17. , 18. , 16.5, 14. , 14.5, 13.5, 16. , 15.5, 16.5, 15.5,
       14.5, 16.5, 19. , 14.5, 15.5, 14. , 15. , 15

In [20]:
min = np.min(acceleration)
max = np.max(acceleration)

normalize= (acceleration-min)/(max-min)
normalize

array([0.23809524, 0.20833333, 0.17857143, 0.23809524, 0.14880952,
       0.11904762, 0.05952381, 0.0297619 , 0.11904762, 0.0297619 ,
       0.11904762, 0.        , 0.08928571, 0.11904762, 0.41666667,
       0.44642857, 0.44642857, 0.47619048, 0.38690476, 0.74404762,
       0.56547619, 0.38690476, 0.56547619, 0.26785714, 0.41666667,
       0.35714286, 0.41666667, 0.32738095, 0.625     , 0.38690476,
       0.44642857, 0.35714286, 0.6547619 , 0.29761905, 0.44642857,
       0.44642857, 0.44642857, 0.44642857, 0.23809524, 0.20833333,
       0.32738095, 0.29761905, 0.20833333, 0.23809524, 0.23809524,
       0.32738095, 0.6547619 , 0.41666667, 0.38690476, 0.35714286,
       0.35714286, 0.68452381, 0.38690476, 0.6547619 , 0.5952381 ,
       0.6547619 , 0.74404762, 0.44642857, 0.53571429, 0.92261905,
       0.68452381, 0.50595238, 0.23809524, 0.23809524, 0.32738095,
       0.29761905, 0.20833333, 0.17857143, 0.32738095, 0.32738095,
       0.26785714, 0.32738095, 0.26785714, 0.35714286, 0.47619

Broadcasting
* Increase all horsepower values by 10% and store the updated values in a new NumPy array. Handle missing data( if any) by replacing it with the mean of the column before applying the increase.

In [21]:
mpg['horsepower'] = pd.to_numeric(mpg['horsepower'], errors = 'coerce')

horsepower = mpg['horsepower'].to_numpy()

In [22]:
mean_horsepower= np.nanmean['horsepower']

NameError: name 'horsepower' is not defined

In [ ]:
null_horsepower=np.nan_to_num(horsepower, nan= mean_horsepower)

In [ ]:
ten_horsepower = null_horsepower * 1.10

In [ ]:
ten_horsepower

Boolean Indexing

Find the average of displacement of cars with an origin of 2(Europe) using numpy Indexing

In [ ]:
displacement = mpg.loc[mpg['origin']== 2]['displacement'].to_numpy()

In [ ]:
average = np.average(displacement)

In [ ]:
average

Matrix Operations

Create a 2D NumPY array containing the column mpg,horsepower, and weight.Compute the dot product of this matrix with a given vector [1,0.5,-0.2]

In [ ]:
vector = np.array([1,0.5,-0.2])

In [ ]:
Combined =mpg[['mpg','horsepower','weight']].to_numpy()

In [ ]:
dot_product = np.dot(Combined,vector)

In [ ]:
dot_product

Sorting
Use Numpy to sort the cars by model_year in descending order and display the first five car name

In [ ]:
sort = mpg.sort_values(by='model year', ascending=False)

In [ ]:
car_name = sort['car name'].head

In [ ]:
car_name

Correlation
Compute the pearson correlatio coefficient between mpg and weight using Numpy

In [ ]:
Co_mpg = mpg['mpg'].to_numpy()
Co_weight = mpg['weight'].to_numpy()

In [ ]:
corr = np.corrcoef(Co_mpg,Co_weight)

In [ ]:
corr

In [ ]:
cor_coef = corr[0,1]

In [ ]:
cor_coef

Conditional Aggregates

Calculate the mean mpg for cars grouped by number of cylinders using numpy technique

In [23]:
mpg = mpg.apply(pd.to_numeric, errors='coerce')

In [24]:
cylinder = mpg['cylinders'].to_numpy()

In [25]:
unique = np.unique(cylinder)

In [27]:
for cyl in unique:
    mean_mpg = mpg[cylinder == cyl].mean()

In [28]:
mean_mpg

mpg               14.963107
cylinders          8.000000
displacement     345.009709
horsepower       158.300971
weight          2472.009709
acceleration      12.955340
model year        73.902913
origin             1.000000
car name                NaN
dtype: float64